// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "OCONNOR SMOKE",
  domain: "oconnorsmokecannabis.com",
  city: "East York",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-east-york",
  address: "132 O'Connor Dr Unit B, East York, ON M4J 2S4",
  streetAddress: "132 O'Connor Dr Unit B",
  postalCode: "M4J 2S4",
  phone: "(647) 924-1664",
  phoneIntl: "+16479241664",
  neighborhood: "O’Connor / East York",
  nearbyAreas: ["O\u2019Connor Drive", "East York", "Woodbine", "St. Clair East", "Victoria Park", "Parkview Hills", "Topham Park", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: "43.6532",
  longitude: "-79.3832",
  hours: ["Open Daily: 10:00 AM - 2:30 AM"],
  seoTitle: "East York Dispensary on O’Connor Dr | O’Connor Smoke Cannabis",
  metaDescription: "Walk-in East York cannabis store at 132 O’Connor Dr Unit B. Serving Danforth, Woodbine, and Don Mills. Call (647) 924-1664. Adults 19+.",
  localLandmarks: ["O\u2019Connor Drive", "East York", "Woodbine"],
  introVariant: "O’Connor Smoke Cannabis is the East York walk-in dispensary at 132 O’Connor Drive, Unit B. The store serves East York, the Danforth, Woodbine, Pape-to-Coxwell side streets, and shoppers coming off the DVP / Don Mills edge.",
  neighborhoodDescription: "Located in the vibrant O’Connor / East York district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Parking spaces are available in the plaza parking lot",
  transitNote: "Accessible by local TTC bus routes serving the surrounding East York area.",
  sectionTitle: "Serving Customers Near O’Connor Drive and East York"
};
