// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "OCONNOR SMOKE",
  domain: "oconnorsmokecannabis.com",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "132 O'Connor Dr Unit B, Toronto, ON M4J 2S4",
  streetAddress: "132 O'Connor Dr Unit B",
  postalCode: "M4J 2S4",
  phone: "(647) 924-1664",
  phoneIntl: "+16479241664",
  neighborhood: "O’Connor / East York",
  nearbyAreas: ["O\u2019Connor Drive", "East York", "Woodbine", "St. Clair East", "Victoria Park", "Parkview Hills", "Topham Park", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: "43.6532",
  longitude: "-79.3832",
  hours: ["Open Daily: 10:00 AM - 12:00 AM"],
  seoTitle: "OCONNOR SMOKE | Weed Dispensary in Toronto",
  metaDescription: "OCONNOR SMOKE is a local weed dispensary in Toronto offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["O\u2019Connor Drive", "East York", "Woodbine"],
  introVariant: "OCONNOR SMOKE is your welcoming neighborhood weed dispensary in Toronto, located at 132 O'Connor Dr Unit B near O’Connor / East York. We carry a massive selection of weed, cannabis flower, pre-rolls, edibles, THC vapes, concentrates, and smoking accessories for adults 19+. Conveniently located near East York, our cannabis store and weed shop is designed to make finding the perfect strain easy and accessible.",
  neighborhoodDescription: "Located in the vibrant O’Connor / East York district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Parking spaces are available in the plaza parking lot",
  transitNote: "Accessible by local TTC bus routes serving the surrounding East York area.",
  sectionTitle: "Serving Customers Near O’Connor Drive and East York"
};
